apiVersion: v1
kind: Template
metadata:
  name: sync2jira-sync-page-template
  app: sync2jira-sync-page
labels:
  app: sync2jira-sync-page
parameters:
- name: CA_URL
  displayName: CA URL used for sync2jira
  required: true
- name: DEFAULT_SERVER
  displayName: Default server to use for mailing
  required: true
- name: DEFAULT_FROM
  displayName: Default from to use for mailing
  required: true
- name: USER
  displayName: JIRA username
  required: true
- name: CONFLUENCE_SPACE
  displayName: Confluence space
  required: true
  value: "mock_confluence_space"
- name: INITIALIZE
  displayName: True/False Initialize our repos on startup
  value: "0"
- name: IMAGE_URL
  displayName: Image URL:TAG to pull from
  value: "quay.io/redhat-aqe/sync2jira:sync-page"
- name: JIRA_PNT_PASS
  displayName: PNT password in base64
  required: true
- name: JIRA_OMEGAPRIME_PASS
  displayName: Omegaprime password in base64
  required: true
- name: GITHUB_TOKEN
  displayName: GitHub token in base64
  required: true
- name: PAAS_DOMAIN
  displayName: Domain to use for the service
  required: true
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: sync2jira-sync-page
    annotations:
      openshift.io/display-name: sync2jira-sync-page
    name: sync2jira-sync-page
  spec:
    lookupPolicy:
      local: false
    tags:
      - from:
          kind: DockerImage
          name: ${IMAGE_URL}
        name: latest
        referencePolicy:
          type: Source
- apiVersion: v1
  kind: Secret
  metadata:
    name: sync2jira-secret
    labels:
      app: sync2jira-stage
  data:
    jira_pnt_pass: |-
      ${JIRA_PNT_PASS}
    jira_omegaprime_pass: |-
      ${JIRA_OMEGAPRIME_PASS}
    sync2jira-confluence: |-
      ${SYNC2JIRA_CONFLUENCE_PASS}
    github_token: |-
      ${GITHUB_TOKEN}
- apiVersion: v1
  kind: Route
  metadata:
    name: sync2jira-sync-page
    labels:
      app: sync2jira-sync-page
  spec:
    host: sync2jira-page-sync.${PAAS_DOMAIN}
    to:
      kind: Service
      name: sync2jira-sync-page
    port:
      targetPort: http
- apiVersion: v1
  kind: Service
  metadata:
    name: sync2jira-sync-page
    labels:
      app: sync2jira-sync-page
  spec:
    selector:
      service: sync2jira-sync-page
    ports:
      - name: http
        port: 80
        targetPort: http
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: sync2jira-sync-page
    labels:
      app: sync2jira-sync-page
  spec:
    selector:
      service: sync2jira-sync-page
    template:
      metadata:
        labels:
          app: sync2jira-sync-page
          service: sync2jira-sync-page
      spec:
        containers:
        - name: sync2jira-sync-page-container
          image: sync2jira-sync-page:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5000
          volumeMounts:
            - name: fedmsgd-volume
              mountPath: /etc/fedmsg.d
              readOnly: true
          env:
            - name: BASE_URL
              value: 0.0.0.0
            - name: REDIRECT_URL
              value: sync2jira-page-sync.${PAAS_DOMAIN}
            - name: INITIALIZE
              value: ${INITILIZE}
            - name: CA_URL
              value: ${CA_URL}
            - name: DEFAULT_SERVER
              value: ${DEFAULT_SERVER}
            - name: DEFAULT_FROM
              value: ${DEFAULT_FROM}
            - name: USER
              value: ${USER}
            - name: SYNC2JIRA_PNTJIRA_PASS
              valueFrom:
                secretKeyRef:
                  key: jira_pnt_pass
                  name: sync2jira-secret
            - name: SYNC2JIRA_OMEGAPRIME_PASS
              valueFrom:
                secretKeyRef:
                  key: jira_omegaprime_pass
                  name: sync2jira-secret
            - name: SYNC2JIRA_GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  key: github_token
                  name: sync2jira-secret
            - name: CONFLUENCE_SPACE
              value: ${CONFLUENCE_SPACE}
            - name: INITILIZE
              value: ${INITILIZE}
        volumes:
          - name: fedmsgd-volume
            configMap:
              name: fedmsgd
    triggers:
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - sync2jira-sync-page-container
          from:
            kind: ImageStreamTag
            name: sync2jira-sync-page:latest
      - type: ConfigChange
